---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: firefly-telegram
  labels:
    app: firefly-iii
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi